# Generated by Django 4.2.6 on 2023-11-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Zona Norte', 'ZONA NORTE'), ('Zona Sul', 'ZONA SUL'), ('Zona Leste', 'ZONA LESTE'), ('Zona Oeste', 'ZONA OESTE')], default='', max_length=100),
        ),
    ]
